USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

AVATAR_UPLOAD_PATH = "avatars/"
USERS_PER_PAGE = 12

GIT_HOST = "github.com"

INVALID_GIT_URL_MESSAGE = "Только Github"
INVALID_PHONE_MESSAGE = "Неверный формат номера телефона (пример: +79991111111)"

PHONE_REGEX = r"^(\+7|8)\d{10}$"