PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PROJECT_STATUS_CHOICES = [
    (PROJECT_STATUS_OPEN, "Open"),
    (PROJECT_STATUS_CLOSED, "Closed"),
]

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = max(
    len(status) for status, _ in PROJECT_STATUS_CHOICES
)

PROJECTS_PER_PAGE = 12

GIT_HOST = "github.com"
INVALID_GIT_URL_MESSAGE = "Только Github"

JSON_STATUS_OK = "ok"